### PR TITLE
Add --sourcify to `hardhat ignition verify` and `deploy`

### PR DESCRIPTION
**Pull request by CedarMist**
Closes: #736

This adds the `--sourcify` and `--etherscan` flags to the `verify` and `deploy` tasks.

The backward compatible `--verify` option selects both.

[sourcify](https://sourcify.dev/) is already supported by hardhat-verify, so `pnpm-lock.yaml` didn't need modifying.

The [hardhat documentation](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#usage) states that you have to set `sourcify.enabled = true` in your `hardhat.config.js` file, but given that no API key is required it is available by default.

Example deployment:

```shell
$ pnpm hardhat ignition deploy --network sepolia --etherscan  --sourcify ignition/modules/Lock.js 
✔ Confirm deploy to network sepolia (11155111)? … yes

Deployed Addresses

LockModule#Lock - 0x1D0cd93efFfBb44C94b7909cD9B7B02F14098063

Verifying deployed contracts...

 https://sepolia.etherscan.io/address/0x1D0cd93efFfBb44C94b7909cD9B7B02F14098063#code

 https://repo.sourcify.dev/contracts/full_match/11155111/0x1D0cd93efFfBb44C94b7909cD9B7B02F14098063/

```

Existing deployed contracts can be also be verified with sourcify:

```shell
$ pnpm hardhat ignition verify --network sepolia --sourcify  chain-11155111

Verifying deployed contracts...

 https://repo.sourcify.dev/contracts/full_match/11155111/0x1D0cd93efFfBb44C94b7909cD9B7B02F14098063/
```

### CODE REVIEW

**Comment by CedarMist** [comment]
After merging I need to do update docs at:

 - [ ] https://docs.sourcify.dev/docs/how-to-verify/
 - [ ] https://hardhat.org/ignition/docs/guides/verify

**Comment by CedarMist** [comment]
@zoeyTM Can we re-run the workflow? I fixed the minor lint bug, and test error where it would fail if etherscan is not configured (such as when testing sourcify alone)

**Comment by HarryR** [comment]
@kanej Any update? It's been a while

**Comment by kanej** [comment]
We massively appreciate the work put in here, but I am afraid we don't intend to merge this PR.

Hardhat is currently in the process of a large upgrade as part of V3, the underlying `hardhat-verify` plugin is being overhauled including the `sourcify` support. At that point Ignition, with its own verify support, will be converted over to the new architecture. We want to tackle `sourcify` support in that context.

**Pull request closed without merging**
