### PR TITLE
Lazy load external packages within plugin (PR 2)

### LINKED ISSUE #13: Load Ignition core lazily in the hardhat plugin
Ignition uses some heavy packages (ink, react), therefore the hardhat plugin shouldn't load Ignition directly. Instead, it should be lazy-loaded when needed.

### PR DESCRIPTION
**Pull request by zoeyTM**
fixes #13

### CODE REVIEW

**Comment by fvictorio** [comment]
I tested this locally and `npx hardhat` goes from taking 500ms to taking 2000ms when including the `hardhat-ignition` plugin.

I suspect the cause is this one:

```typescript
export { buildModule } from "@nomicfoundation/ignition-core";
```

I'm not 100% sure what's the best way to do this "dynamic". This monstrosity seems to compile fine:

```typescript
export const buildModule: typeof import("@nomicfoundation/ignition-core").buildModule =
  (...args) => {
    const { buildModule: coreBuildModule } =
      require("@nomicfoundation/ignition-core") as typeof import("@nomicfoundation/ignition-core");

    return coreBuildModule(...args);
  };
```

**Comment by fvictorio** [comment]
Ugh, I tried that using `main`, sorry, I'll give it another try in this branch -_-

**Comment by fvictorio** [comment]
Ok, these are the proper measurements:

1. `npx hardhat` without the ignition plugin: 500ms
2. `npx hardhat` with the current version of ignition: 2000ms
3. `npx hardhat` with these changes: 1500ms
4. `npx hardhat` with these changes plus the change in my comment above: 550ms

So yeah, we should make that change (or an equivalent one)

**Comment by kanej** [comment]
@fvictorio, @schaable Would the eslint plugin work for our repo?

**Comment by fvictorio** [comment]
I think so. We should make some changes and publish it.

**Comment by fvictorio** [comment]
Opened https://github.com/NomicFoundation/hardhat/issues/4423

**Comment by alcuadrado** [comment]
I think this looks good enough. Let's merge it, and then we revisit it once the slow imports eslint plugin gets published.

**Review by alcuadrado — APPROVED** [review]

**Pull request merged**
